openapi: 3.0.1
info:
  title: Sample application for openapi specs.
  description: This document contains REST endpoint related to opeanpai spec tutorial.
  termsOfService: https://www.sample.shashtra.com/terms
  contact:
    name: Sample app support
    url: https://sample.dev-support.shashtra.com
    email: dev-support@shashtra.com
  version: 1.0.0
externalDocs:
  description: This doc contains more information related to these apis.
  url: https://github.com/hariom454/openapi-demo/blob/master/README.md
servers:
- url: http://localhost:8080
  description: Local
- url: https://dev-sample-app.shashtra.com/v1
  description: Dev
tags:
- name: Sample APIs
  description: This collection is for sample apis for openapi tutorial.
paths:
  /user/search:
    get:
      tags:
      - Sample APIs
      operationId: searchUser
      parameters:
      - name: emailId
        in: query
        description: user email id.
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
      security:
      - requestAuth: []
  /users:
    get:
      tags:
      - Sample APIs
      description: Get All user details.
      operationId: getAllUserDetails
      responses:
        "200":
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        "400":
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
      - requestAuth: []
    post:
      tags:
      - Sample APIs
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
      security:
      - requestAuth: []
  /users/{userId}:
    get:
      tags:
      - Sample APIs
      operationId: getUserDetails
      parameters:
      - name: userId
        in: path
        description: userId to get user details.
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
      security:
      - requestAuth: []
components:
  schemas:
    CreateUserRequest:
      type: object
      properties:
        emailAddress:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        userId:
          type: string
          readOnly: true
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    User:
      type: object
      properties:
        emailAddress:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        userId:
          type: string
          readOnly: true
  securitySchemes:
    requestAuth:
      type: apiKey
      name: Authorization
      in: header
