openapi: 3.0.1
info:
  contact:
    email: dev-support@shashtra.com
    name: Sample app support
    url: https://sample.dev-support.shashtra.com
  description: This document contains REST endpoint related to opeanpai spec tutorial.
  termsOfService: https://www.sample.shashtra.com/terms
  title: Sample application for openapi specs.
  version: 1.0.0
externalDocs:
  description: This doc contains more information related to these apis.
  url: https://github.com/hariom454/openapi-demo/blob/master/README.md
servers:
- description: Local
  url: http://localhost:8080
- description: Dev
  url: https://dev-sample-app.shashtra.com/v1
tags:
- description: This collection is for sample apis for openapi tutorial.
  name: Sample APIs
paths:
  /user/search:
    get:
      operationId: searchUser
      parameters:
      - description: user email id.
        in: query
        name: emailId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
          description: OK
      security:
      - requestAuth: []
      tags:
      - Sample APIs
  /users:
    get:
      description: Get All user details.
      operationId: getAllUserDetails
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: Request succeeded.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request.
      security:
      - requestAuth: []
      tags:
      - Sample APIs
    post:
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
          description: OK
      security:
      - requestAuth: []
      tags:
      - Sample APIs
  /users/{userId}:
    get:
      operationId: getUserDetails
      parameters:
      - description: userId to get user details.
        in: path
        name: userId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
          description: OK
      security:
      - requestAuth: []
      tags:
      - Sample APIs
components:
  schemas:
    CreateUserRequest:
      type: object
      properties:
        emailAddress:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        userId:
          type: string
          readOnly: true
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    User:
      type: object
      properties:
        emailAddress:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        userId:
          type: string
          readOnly: true
  securitySchemes:
    requestAuth:
      in: header
      name: Authorization
      type: apiKey
